### ISSUE TITLE
1.2.0 version requires Ruby 2.1 without need

### ISSUE THREAD

**Issue by christofdamian** [sethvargo/buff-ignore#4]
We just run into a problem with Berkshelf on AWS Opsworks, which over some dependencies also relies on buff-ignore. The 1.2.0 update stopped working because Opsworks is still on Ruby 2.0. 

We are also talking to the ridley project to lock the buff-ignore requirement to 1.1.1.  

I realize that Ruby 2.0 is obsolete, but this change is not necessary.

**Comment by sethvargo** [comment]
@tas50

**Comment by tas50** [comment]
@christofdamian Ruby 2.1 became the new requirement in the 1.2.0 release as Ruby releases less than 2.1 are now officially end of life. Ruby 2.1 no longer receives bug fixes, but does receive security fixes, which makes it the oldest release we're comfortable supporting. A large portion of the Ruby ecosystem has recently removed support for Ruby 2.0, and some even 2.1. This includes projects like rack that are used throughout the Ruby ecosystem. I'm open to pinning buff-ignore for a last release of ridley that supports unsupported Ruby releases, but this is going to be a temporary fix only. The master branch of berkshelf already support Ruby 2.1+ only and I have a PR open in Ridley to support 2.1+ only. Without those pins we can't test Berkshelf due to upstream projects pulling support for older Rubies.

I understand that upgrading in Opsworks is a pretty large task, but I'd recommend you consider an upgrade, or using rbenv/rvm to be able to run the latest Ruby releases on your node outside of the Chef installation. As time goes on it's going to become harder and harder to run unsupported Ruby releases without a complex Gem pinning scheme on your side.

**Comment by christofdamian** [comment]
I understand. I would just prefer if libraries would just require what they
are using though.

For now we have removed berkshelf from our stack, because we couldn't
deploy any more otherwise.

Thanks for the quick response!

**Comment by tas50** [comment]
Ridley 4.6.1 has been released with a more aggressive pin on buff-ignore that allows for Ruby 1.9/2.0. We will be releasing Ridley 5.0 with dropped Ruby 1.9/2.0 support and shortly after that Berkshelf support with the same. You can pin to the current berkshelf release if you need to use legacy Ruby releases.

**Comment by christofdamian** [comment]
Very cool, thanks for the help.

We will do that and move to newer chef and opsworks version asap.
